/**
 * Request bodies for the upload/video API. Imported by route handlers AND client
 * components, so it must only import `@/shared/enums` (never the `@/shared` barrel,
 * which pulls Mongoose into the browser bundle).
 */
import { z } from "zod";

import { CLIP_REQUEST } from "@/shared/clip-sets";
import { CLIP_INTENTS, LANGUAGES } from "@/shared/enums";

export const objectIdString = z.string().regex(/^[a-f0-9]{24}$/, "must be a 24-character id");

/** The choices on the new-video form, in the order shown. */
export const FORM_INTENTS = [
  "best",
  "sports",
  "news",
  "interview",
  "educational",
  "funny",
  "emotional",
  "motivational",
] as const satisfies readonly (typeof CLIP_INTENTS)[number][];

/** "Find new clips" (Step 14) offers the same focuses plus "custom": the user describes what to find. */
export const REQUEST_INTENTS = [...FORM_INTENTS, "custom"] as const;

/** POST /api/videos/:id/clip-requests — find a new set of clips for a finished video. */
export const clipRequestSchema = z
  .object({
    intent: z.enum(REQUEST_INTENTS),
    query: z.string().trim().max(CLIP_REQUEST.queryMaxChars).optional(),
  })
  .refine((v) => v.intent !== "custom" || (v.query ?? "").length >= CLIP_REQUEST.queryMinChars, {
    message: `Describe what to look for (at least ${CLIP_REQUEST.queryMinChars} characters).`,
    path: ["query"],
  })
  .transform((v) => ({ intent: v.intent, query: v.intent === "custom" ? (v.query ?? null) : null }));
export type ClipRequestInput = z.input<typeof clipRequestSchema>;

/** POST /api/uploads — ask for a signed upload before sending the file. */
export const requestUploadSchema = z.object({
  fileName: z.string().trim().min(1).max(500),
  sizeBytes: z.number().int().positive(),
  /** Read by the browser from the file's metadata; null when it couldn't be read. */
  durationMs: z.number().int().nonnegative().nullable(),
  contentType: z.string().max(100),
});
export type RequestUploadInput = z.infer<typeof requestUploadSchema>;

/** POST /api/videos — the file is in Cloudinary; create the video. */
export const finalizeUploadSchema = z.object({
  videoId: objectIdString,
  originalFilename: z.string().trim().min(1).max(500),
  language: z.enum(LANGUAGES),
  intent: z.enum(FORM_INTENTS),
  /** The form won't submit without the checkbox; the server re-checks it. */
  permission: z.literal(true),
});
export type FinalizeUploadInput = z.infer<typeof finalizeUploadSchema>;

/** POST /api/videos/youtube — process a YouTube video by link. */
export const submitYouTubeSchema = z.object({
  url: z.string().trim().min(1).max(500),
  /** Generated by the form once per submission, so a double click can't create two videos. */
  clientRequestId: z.uuid(),
  language: z.enum(LANGUAGES),
  intent: z.enum(FORM_INTENTS),
  permission: z.literal(true),
});
export type SubmitYouTubeInput = z.infer<typeof submitYouTubeSchema>;

/** Accepted by the file picker and checked before upload. Cloudinary re-checks the content. */
export const ACCEPTED_VIDEO_TYPES = ["video/mp4", "video/quicktime", "video/webm", "video/x-matroska", "video/x-m4v"];
